name: Generate CML Report
 
on: [push]
 
jobs:
  generate_cml_report:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - 8080:8080
      volumes:
        - /home/runner/work/GCBM.Belize/Standalone_GCBM:/server
      options: --name gcbm-belize
    steps:
      - name: Install NPM # Need this for the CML setup
        id: install_npm
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y nodejs npm
      - name: Setup CML
        id: setup_cml
        uses: iterative/setup-cml@v1
      - name: Checkout gcbm-container branch
        id : checkout_gcbm_container_branch
        uses: actions/checkout@v2
        with:
          ref: gcbm-container
      - name: Run CML
        id: run_cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo "[1/3] Remove output"
          
          /bin/bash -c "rm -rf Standalone_GCBM/gcbm_project/output"
          
          echo "[2/3] Docker execute commands"
          
          /bin/bash -c "cd /server/gcbm_project && /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json &> temp.md"
          
          echo "[3/3] Send the report as a comment"
          
          cml-send-comment  Standalone_GCBM/gcbm_project/temp.md
