name: test-run
 
on: [push]
 
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
        with:
          ref: gcbm-container

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          echo "[1/5] Pulling image"
          
          docker pull ghcr.io/harshcasper/flint.gcbm-cloud:latest
          
          echo "[2/5] Remove output"
          
          rm -rf Standalone_GCBM/gcbm_project/output
          
          echo "[3/5] Create and run container, and execute commands"
          
          docker run -d -v "$(pwd)/Standalone_GCBM":/server -p 8080:8080 --name gcbm-belize ghcr.io/harshcasper/flint.gcbm-cloud
          
          echo "[4/5] Docker execute commands"
          
          docker exec gcbm-belize /bin/bash -c "cd /server/gcbm_project && /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json &> temp.md && exit"
          
          echo "[5/5] Send the report as a comment"
          
          cml-send-comment  Standalone_GCBM/gcbm_project/temp.md
