name: Generate CML Report
 
on: [push]
 
jobs:
  generate_cml_report:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - name: Remove GCBM output
        id: remove_gcbm_output
        run: |
          rm -rf Standalone_GCBM/gcbm_project/output
      - name: Install NPM # Need this for the CML setup
        id: install_npm
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y nodejs npm
          node -v
      - name: Setup CML
        id: setup_cml
        uses: iterative/setup-cml@v1
      - name: Checkout gcbm-container branch
        id : checkout_gcbm_container_branch
        uses: actions/checkout@v2
        with:
          ref: gcbm-container
      - name: Run CML
        id: run_cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo $(ls)
          echo $GITHUB_WORKSPACE
          echo $(ls $GITHUB_WORKSPACE)
          cd Standalone_GCBM/gcbm_project
          
          touch temp.md
          
          echo "[1/2] Docker execute commands"
          
          /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json &>temp.md
          
          echo $(ls)
          
          echo "[2/2] Send the report as a comment"
          
          cml-send-comment temp.md
