name: test-run
 
on: [push]
 
jobs:
  run:
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          cd ../

          git clone -b gcbm-container https://github.com/moja-global/flint.cloud
          
          cd GCBM.Belize
          
          rm -r Standalone_GCBM/gcbm_project/output
 
          docker-compose build
          
          docker-compose up -d
          
          docker exec -it gcbm-belize /bin/bash
          
          cd /server/gcbm_project
          
          nohup /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json
          
          mv nohup.out report.md
          
          cml-send-comment report.md