name: Generate CML Report
 
on: [push]
 
jobs:
  generate_cml_report:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/harshcasper/flint.gcbm-cloud
      ports:
        - "8080:8080"
    steps:
      - name: Remove GCBM output
        id: remove_gcbm_output
        run: |
          rm -rf Standalone_GCBM/gcbm_project/output
      - name: Setup Node # Need this for the CML setup
        id: setup_node
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Min version 12 is needed
      - name: Setup CML
        id: setup_cml
        uses: iterative/setup-cml@v1
      - name: Checkout gcbm-container branch
        id : checkout_gcbm_container_branch
        uses: actions/checkout@v2
        with:
          ref: gcbm-container
      - name: Install simplejson
        id: install_simplejson
        run: pip install simplejson
      - name: Install sqlalchemy
        id: install_sqlalchemy
        run: pip install sqlalchemy      
      - name: Run Moja CLI
        id: run_moja_cli
        run: |
        
          echo "[0/3] Change permissions"
          chmod 664 Standalone_GCBM/gcbm_project/
          echo "[1/3] Change working directory to gcbm_project"
          cd Standalone_GCBM/gcbm_project
          
          echo "[2/3] Run Moja CLI"
          /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json &> temp.md
          chmod 664 output/gcbm_output.db
          chmod 664 output/compiled_gcbm_output.db
          echo $(ls)
          echo "[3/3] Compile GCBM Results"
          python3 ../tools/CompileGCBMResults/compileresults.py sqlite:///output/gcbm_output.db --output_db sqlite:///output/compiled_gcbm_output.db

      - name: CML Upload Report
        id: cml_upload_report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml-send-comment temp.md

