name: Generate CML Report
 
on: [push]
 
jobs:
  generate_cml_report:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      volumes:
      - ./Standalone_GCBM:/server
      ports:
        - "8080:8080"
      options: --name gcbm-belize
    steps:
      - name: Remove GCBM output
        id: remove_gcbm_output
        run: |
          rm -rf Standalone_GCBM/gcbm_project/output
      - name: Install NPM # Need this for the CML setup
        id: install_npm
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y nodejs npm
      - name: Setup CML
        id: setup_cml
        uses: iterative/setup-cml@v1
      # - name: Checkout gcbm-container branch
      #   id : checkout_gcbm_container_branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: gcbm-container
      - name: Run CML
        id: run_cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          echo "[1/2] Docker execute commands"
          
          sh -c "cd /server/gcbm_project && /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json &> temp.md"
          
          echo "[2/2] Send the report as a comment"
          
          cml-send-comment  Standalone_GCBM/gcbm_project/temp.md
